# Generated by Django 4.0.6 on 2022-07-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField()),
                ('clientname', models.CharField(max_length=10)),
                ('createdby', models.CharField(max_length=10)),
                ('createdat', models.DateTimeField()),
            ],
        ),
    ]
